### PR TITLE
add support for Angular 12 + other fixes

### PR DESCRIPTION
**Pull request by jordydejong**
- fix: add support for Angular 12
- create wdio/tsconfig based on provided answers

### CODE REVIEW

**Comment by christian-bromann** [comment]
@jordydejong mind signing the CLA?

**Comment by jordydejong** [comment]
> @jordydejong mind signing the CLA?

sure, let me check who at my company can do this

**Comment by jordydejong** [comment]
> > @jordydejong mind signing the CLA?
> 
> sure, let me check who at my company can do this

should be signed now

**Comment by christian-bromann** [comment]
@jordydejong doesn't seem like .. did you signed with the same email you used in the commit?

**Comment by jordydejong** [comment]
> @jordydejong doesn't seem like .. did you signed with the same email you used in the commit?

No, my CTO signed it.

**Comment by jordydejong** [comment]
> > @jordydejong doesn't seem like .. did you signed with the same email you used in the commit?
> 
> No, my CTO signed it. 

Seems like my commits are missing the user I'd. I'll try to recreate the PR

**Comment by christian-bromann** [comment]
@jordydejong try to set the correct email in your git settings and squash all commits into one

**Comment by christian-bromann** [comment]
Thanks a ton, LGTM 👍

**Review by christian-bromann — APPROVED** [review]

**Pull request merged**
