### PR TITLE
fix(#9): cannot start wdio tests

### LINKED ISSUE #9: Cannot start wdio tests
I added the schematics and tried run the e2e tests. However, there is an error where it says error parsing the config file.

- Installation output
```shell
> ng add @wdio/schematics
ℹ Using package manager: npm
✔ Found compatible package version: @wdio/schematics@1.1.0.
✔ Package information loaded.
 
The package @wdio/schematics@1.1.0 will be installed and executed.
Would you like to proceed? Yes
✔ Package successfully installed.

=========================
WDIO Configuration Helper
=========================

? Where is your automation backend located? On my local machine
? Which framework do you want to use? cucumber
? Do you want to use a compiler? TypeScript (https://www.typescriptlang.org/)
? Where are your feature files located? ./features/**/*.feature
? Where are your step definitions located? ./features/step-definitions/steps.ts
? Do you want WebdriverIO to autogenerate some test files? Yes
? Do you want to use page objects (https://martinfowler.com/bliki/PageObject.html)? Yes
? Where are your page objects located? ./features/pageobjects/**/*.ts
? Which reporter do you want to use? spec, junit
? Do you want to add a service to your test setup? chromedriver
? What is the base url? http://localhost:4200

Installing wdio packages:
- @wdio/local-runner
- @wdio/cucumber-framework
- @wdio/spec-reporter
- @wdio/junit-reporter
- wdio-chromedriver-service
- ts-node
- typescript
- chromedriver
```

- Test output
```shell
> ng run frontend:wdio-run
⠴ Generating browser application bundles (phase: building)...
warn - You have enabled the JIT engine which is currently in preview.
warn - Preview features are not covered by semver, may introduce breaking changes, and can change at any time.
✔ Browser application bundle generation complete.

Initial Chunk Files | Names         |      Size
vendor.js           | vendor        |   2.44 MB
polyfills.js        | polyfills     | 128.50 kB
main.js             | main          |  26.88 kB
styles.css          | styles        |  23.84 kB
runtime.js          | runtime       |   6.62 kB

                    | Initial Total |   2.62 MB

Build at: 2021-10-03T23:58:50.874Z - Hash: 0cdc5040b623167c275a - Time: 7367ms

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


✔ Compiled successfully.
2021-10-03T23:58:51.048Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: /home/xzhan/Development/Projects/desci_online/frontend/wdio.conf.ts: Unexpected token 'export'
Unexpected token 'export'
```

I am using Node 14.17.5 and Angular 12.2.8. Any help is appreciated!

### PR DESCRIPTION
**Pull request by Badisi**
Fix #9

### CODE REVIEW

**Comment by Badisi** [comment]
@christian-bromann, to further improve this PR: 
1) I think we won't need this anymore : [L164-L174](https://github.com/Badisi/webdriverio-schematics/blob/main/src/schematics/webdriverio/index.ts#L164-L174) ? (and it was not even conditioned to `isUsingTypeScript`)

2) We would need to add a default `tsconfigFile` value in `angular.json` [L196](https://github.com/Badisi/webdriverio-schematics/blob/main/src/schematics/webdriverio/index.ts#L196):
    `tsconfigFile: /test/tsconfig.e2e.json`

    But I'm sure on how to get the `/test` here...

**Comment by Badisi** [comment]
Any idea on how to elegantly get the [parsedAnswers](https://github.com/Badisi/webdriverio-schematics/blob/fix-issue-9/src/schematics/webdriverio/index.ts#L130) in here [L188](https://github.com/Badisi/webdriverio-schematics/blob/fix-issue-9/src/schematics/webdriverio/index.ts#L188) ?

I need to do something like :

```ts
const relative = path.relative(process.cwd(), parsedAnswers.destSpecRootPath);
const tsconfigDir = relative.split(path.sep)[0];

const wdioConf = {
  builder: '@wdio/schematics:wdio',
  options: {
    devServerTarget: `${project}:serve`,
    tsconfigFile: `${tsconfigDir}/tsconfig.e2e.json`,
  },
  configurations: {
    production: {
      devServerTarget: `${project}:serve:production`
    }
  }
}
```

**Comment by christian-bromann** [comment]
Shouldn't it be possible to store data in the `SchematicContext` object?

**Comment by Badisi** [comment]
I don't think so...

And anyway `runWizard` and `modifyAngularJson` are running in a `chain` ([L34](https://github.com/Badisi/webdriverio-schematics/blob/fix-issue-9/src/schematics/webdriverio/index.ts#L34)) so we cannot make sure they both run in sequence. I will have to find a better way.

**Comment by Badisi** [comment]
I won't be able to solve it without making many changes.

Running the wizard is optional so I cannot rely on the parsed answers that it returns.
The tsconfig file path has to be determined from within `modifyAngularJson()`.
But this file could have been renamed or moved from a previous wizard installation, and so did the wdio configuration file.
So I'm kind of stuck here...

I guess the wizard shouldn't be optional (why would it be after all ?)
The schematics should decide itself whether wdio is already installed and install it if it's not or do nothing otherwise.
That way everything would be more predictable and easier to automate.

**Comment by Badisi** [comment]
Unfortunately I'm acting blindely on this one because I was not able to mount this project locally to make the proper modifications.

I followed the `development section` in the README and it simply doesn't work.

```sh
$ npx ng add @wdio/schematics
> An unhandled exception occurred: Cannot find module '/Users/badisi/webdriverio-schematics-main/src/schematics/webdriverio/index'
```

**Pull request closed without merging**
